---
- name: Installation de Docker CE sur le client
  hosts: clients #Correspond au groupe de serveur présent dans notre "inventory.ini"
  become: yes #accorde les privilèges sudo

  tasks:
    - name: Mise à jour du cache des paquets
      apt:
        update_cache: yes
      become: yes #accorde les privilèges sudo
# La tâche "apt" avec l'option "update_cache" met à jour le cache des paquets sur le client.



    - name: Installation des dépendances pour Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
      become: yes #accorde les privilèges sudo
# La tâche "apt" installe les dépendances nécessaires pour Docker, y compris les outils HTTPS, Curl, etc.



    - name: Ajout de la clé GPG du référentiel Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present #l'état "Présent" signifie que si l'élément n'est pas créé, il le sera, s'il est présent, il sera mis à jour
      become: yes #accorde les privilèges sudo
# La tâche "apt_key" ajoute la clé GPG du référentiel Docker pour la vérification de l'authenticité des paquets.




    - name: Ajout du référentiel Docker aux sources APT
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present #l'état "present" signifie que si l'élément n'est pas créé, il le sera, s'il est présent, il sera mis à jour
      become: yes #accorde les privilèges sudo
# La tâche "apt_repository" ajoute le référentiel Docker aux sources APT sur le client.

    - name: Installation de Docker CE
      apt:
        name: docker-ce
        state: present
      become: yes #accorde les privilèges sudo
 # La tâche "apt" installe Docker CE sur le client.