---
# FILES (files) => permet d'utiliser un fichier ou une archive stockée localement
- name: copy altermanager
  become: true
  ansible.builtin.copy:
    src: alertmanager-0.25.0.linux-amd64.tar.gz
    dest: /home/shed/alertmanager-0.25.0.linux-amd64.tar.gz
    mode: 0766
    owner: root
    group: root
# TEMPLATES (templates) => appel de fichier(s) permettant de copier le contenu de ce fichier au format j2 où l'on souhaite
- name: Create the service
  ansible.builtin.template:
    dest: /etc/systemd/system/alertmanager.service
    src: alertmanager.service.j2
    owner: root
    group: root
    mode: 0774
# HANDLERS (handlers) => appel de commande(s) via le nom 
  notify:
    - restart systemd-timesyncd
# VARIABLES (defaults/vars) => sert à définir les variables présentes soit dans le playbook, soit dans le rôle
- name: Change SSH port par {{ port_number }} en remplacant la ligne Port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: 'Port {{ port_number }}'

# Commande sans MODULE
- name: Configurer le pare-feu pour autoriser l'accès à l'interface web de Prometheus
  shell: sudo yum update -y






