---

- name: restart systemd-timesyncd
  become: yes
  service:
    name: systemd-timesyncd
    state: restarted

- name: restart chronyd
  become: yes
  service:
    name: chronyd
    state: restarted

- name: restart firewall
  become: yes
  service:
    name: firewall
    state: restarted