---
- hosts: localhost
  become: true
  roles:
    - role: DUMMY_ROLE


# Si on ne veut pas utiliser de role, le playbook serait de type :

---
- name: Install Docker sur Alma 8.7
  hosts: localhost
  become: yes
  tasks:
    - name: Ajouter le dépôt Docker
      yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
        enabled: true
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg
    - name: Mettre à jour la liste des paquets
      yum:
        name: '*'
        state: latest

    - name: remove dnf package
      yum:
        name:
          - podman
          - buildah
        state: absent

    - name: Installer Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        allow_downgrade: true

    - name: Démarrer le service Docker
      systemd:
        name: docker
        enabled: true
        state: started